#!/bin/zsh
if [[ $# < 1 ]]; then
    print "Search the path for pattern matches. Usage: fip <pattern>"
else
    #Search the path for occurances of each argument.
    typeset pattern
    for i do
        pattern=$i(N)
        print -l -- ${^path}/${~pattern}
    done
fi
