#! /bin/zsh

######################
#  Wireless Network  #
######################
# Check if the wireless network is active
WIRELESS_NET="$(ipconfig getpacket en1)";

if [ $WIRELESS_NET ]; then

    # Get the router IP address and use it to scan the network for hosts
    WIRELESS_ROUTER_IP="$(echo $WIRELESS_NET | grep "siaddr" | awk '{print $3}')";
    WIRELESS_SUBNET="$(echo $WIRELESS_ROUTER_IP | sed -E "s/^([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)([0-9]{1,3})/\1*/")";
    WIRELESS_HOSTS=("${(@f)$(nmap -sP -T4 $WIRELESS_SUBNET | grep "Nmap scan report")}");

    # Print the hostname and ipaddress of other devices on the LAN
    print -l " Wireless Net ";
    print "\--------------";
    for HOST in $WIRELESS_HOSTS; do
        HOST_NAME="$(echo $HOST | awk '{print $5}' | sed -E "s/^([A-Za-z0-9_\-]+)\.home/\1/")";
        HOST_IP="$(echo $HOST | awk '{print $6}')";
        HOST_INFO=${HOST_NAME}${HOST_IP}
        print -l $HOST_INFO;
    done
fi;

###################
#  Wired Network  #
###################
# Check if the wireless network is active
WIRED_NET="$(ipconfig getpacket en0)";
if [ $WIRED_NET ]; then
    # Get the router IP address and use it to scan the network for hosts
    WIRED_ROUTER_IP="$(echo $WIRED_NET | grep "siaddr" | awk '{print $3}')";
    WIRED_SUBNET="$(echo $WIRED_ROUTER_IP | sed -E "s/^([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)([0-9]{1,3})/\1*/")";
    WIRED_HOSTS=("${(@f)$(nmap -sP -T4 $WIRED_SUBNET | grep "Nmap scan report")}");


    # Print the hostname and ipaddress of other devices on the LAN
    print -l "   Wired Net  ";
    print -l "\--------------";
    for HOST in $WIRED_HOSTS; do
        HOST_NAME="$(echo $HOST | awk '{print $5}' | sed -E "s/^([A-Za-z0-9_\-]+)\.home/\1/")";
        HOST_IP="$(echo $HOST | awk '{print $6}')";
        HOST_INFO=${HOST_NAME}${HOST_IP}
        print -l $HOST_INFO;
    done
fi;

